#!/usr/bin/env bash

# Цвета для вывода
LIGHTGREEN="\033[1;32m"
NOCOLOR="\033[0m"

echo -e "executing: ${LIGHTGREEN}          BORIS TOOL ${NOCOLOR}"
echo "----------------------------"

chmod +x etc/*.bms

# Проверка наличия директории BORIS_TOOL, если нет - создание
if [[ ! -d "/sdcard/Download/BORIS_TOOL" ]]; then
  mkdir -p /sdcard/Download/BORIS_TOOL
fi

pak_folder="/data/data/com.termux/files/home/PakTool/pak_folder"
output_folder="/data/data/com.termux/files/home/OBB_UNPACK/output"

# Проверка наличия необходимых программ
command -v qemu-i386 >/dev/null 2>&1 || { echo >&2 "qemu-i386 is required but it's not installed. Aborting."; exit 1; }
command -v quickbms_4gb_files >/dev/null 2>&1 || { echo >&2 "quickbms is required but it's not installed. Aborting."; exit 1; }

unpacking () {
  qemu-i386 $PREFIX/share/quickbms/quickbms_4gb_files etc/*.bms "$pak_folder/$(basename "$selected_file")" "$output_folder"
}

repacking () {
  qemu-i386 $PREFIX/share/quickbms/quickbms_4gb_files -w -r etc/*.bms "$selected_file" /sdcard/Download/file_for_repack
}

function unpack {
  prompt="Please select a file to unpack:"
  options=($(find /sdcard/Download/BORIS_TOOL -name "*.pak" -o -name "*.obb"))

  PS3="$prompt "
  select opt in "${options[@]}" "Quit"; do 
    if (( REPLY == 1 + ${#options[@]} )); then
      echo "Operation canceled."
      exit

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )); then
      selected_file="${options[$REPLY-1]}"
      echo "You picked $selected_file which is file $REPLY"

      mkdir -p "$pak_folder"
      cp "$selected_file" "$pak_folder/"
      
      unpacking
      
      if [[ $? -eq 0 ]]; then
        echo "Unpacking completed successfully."
      else
        echo "An error occurred during unpacking."
      fi
      
      rm -rf "$pak_folder"
      break

    else
      echo "Invalid option. Try another one."
    fi
  done
}

function repack {
  prompt="Please select a file to repack:"
  options=($(find /sdcard/Download/BORIS_TOOL -name "*.pak" -o -name "*.obb"))

  PS3="$prompt "
  select opt in "${options[@]}" "Quit"; do 
    if (( REPLY == 1 + ${#options[@]} )); then
      echo "Operation canceled."
      exit

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )); then
      selected_file="${options[$REPLY-1]}"
      echo "You picked $selected_file which is file $REPLY"
      
      repacking
      
      if [[ $? -eq 0 ]]; then
        echo "Repacking completed successfully."
      else
        echo "An error occurred during repacking."
      fi
      
      break

    else
      echo "Invalid option. Try another one."
    fi
  done
}

PS3='Please enter your choice: '
options=("Unpack" "Repack" "Quit")
select opt in "${options[@]}"
do
  case $opt in
    "Unpack")
      unpack
      break
      ;;
    "Repack")
      repack
      ;;
    "Quit")
      break
      ;;
    *) echo "invalid option $REPLY";;
  esac
done